sudo: false
dist: xenial

cache:
  directories:
    - ~/.cache.pip

language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy3.5-6.0.0

install:
  - pip install -e .\[dev\]

script:
  - flake8 click_aliases examples tests setup.py -v --show-source
  - py.test tests --cov click_aliases --cov-report term-missing
  - pip install 'click>6,<7'
  - py.test tests --cov click_aliases --cov-report term-missing --cov-append

after_success:
  - coveralls

